service: workshop-node

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless_personal
  region: eu-west-1
  stage: dev
  tracing: true
  environment:
    log_level: INFO
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing

custom:
  serverless-iam-roles-per-function:
    defaultInherit: true

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api:
        Fn::Join:
          - ''
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.eu-west-1.amazonaws.com/dev/restaurants"
      orders_api:
        Fn::Join:
          - ''
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.eu-west-1.amazonaws.com/dev/orders"
      cognito_user_pool_id: ${ssm:/workshop-node/dev/cognito_user_pool_id}
      cognito_client_id: ${ssm:/workshop-node/dev/cognito_web_client_id}
    iamRoleStatements:
      - Effect: Allow
        Action: execute-api:Invoke
        Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants

  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants/
          method: get
          authorizer: aws_iam
    environment:
      restaurants_table: ${ssm:/workshop-node/dev/table_name}
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:scan
        Resource:
          Fn::GetAtt:
            - restaurantsTable
            - Arn

  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/${ssm:/workshop-node/dev/cognito_user_pool_id}
    environment:
      restaurants_table: ${ssm:/workshop-node/dev/table_name}
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:scan
        Resource:
          Fn::GetAtt:
            - restaurantsTable
            - Arn

  place-order:
    handler: functions/place-order.handler
    events:
      - http:
          path: /orders
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/${ssm:/workshop-node/dev/cognito_user_pool_id}
    environment:
      order_events_stream: ${ssm:/workshop-node/dev/stream_name}
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource:
          Fn::GetAtt:
            - orderEventsStream
            - Arn

  notify-restaurant:
    handler: functions/notify-restaurant.handler
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - orderEventsStream
              - Arn
    environment:
      order_events_stream: ${ssm:/workshop-node/dev/stream_name}
      restaurant_notification_topic:
        Ref: restaurantNotificationTopic
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource:
          Fn::GetAtt:
            - orderEventsStream
            - Arn
      - Effect: Allow
        Action: sns:Publish
        Resource:
          - Ref: restaurantNotificationTopic

resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${ssm:/workshop-node/dev/table_name}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    CognitoUserPoolMyUserPool:
      Type: AWS::Cognito::UserPool
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${ssm:/workshop-node/dev/stream_name}
        ShardCount: 1
    restaurantNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${ssm:/workshop-node/dev/restaurant_topic_name}
        TopicName: ${ssm:/workshop-node/dev/restaurant_topic_name}
